### PR TITLE
Urban Sound 8K Dataset

### LINKED ISSUE #67: Urban Sound 8K dataset
Claimed Set -:  
[Urban Sound 8K dataset](https://urbansounddataset.weebly.com/urbansound8k.html) 

About-
Contains Urban sounds from 10 classes like an air conditioner, dog bark, drilling, siren, street music, etc.

### PR DESCRIPTION
**Pull request by abhijeet007rocks8**
Closes #67

### CODE REVIEW

**Comment by nirbarazida** [comment]
Hi @abhijeet007rocks8 

Thank you for your contribution.
Please add a link to the DagsHub repo in the README and we'll be more than happy to merge.

**Comment by abhijeet007rocks8** [comment]
@nirbarazida Added the link to DAGsHub Repo in README.

**Comment by nirbarazida** [comment]
Hi @abhijeet007rocks8 ,

Did you upload the dataset to [dagshub](https://dagshub.com/dashboard)?

**Comment by Rutam21** [comment]
@nirbarazida There is no such dataset available for Urban Sound 8K on DagsHub. As it's already been a year and the PR is not worked upon, I would like to claim this dataset for myself and add a PR for this completing all required steps. Thanks.

**Comment by nirbarazida** [comment]
@Rutam21 that's fair. I'll close the PR.

**Pull request closed without merging**
